from unittest.mock import patch
from app.services.llm_service import classify_missing_categories_batch, generate_narrative_summary
from app.config import settings


@patch('app.services.llm_service.call_gemini_api')
def test_classify_missing_categories_batch(mock_gemini):
    # Mock the LLM response
    mock_gemini.return_value = [
        {"txn_id": "1", "category": "Food"}
    ]
    
    settings.gemini_api_key = "test_key"
    
    records = [
        {"txn_id": "1", "merchant": "Unknown Cafe", "category": "Uncategorised", "notes": ""},
        {"txn_id": "2", "merchant": "Amazon", "category": "Shopping", "notes": ""}
    ]
    
    processed = classify_missing_categories_batch(records)
    
    # Assert LLM was called only for uncategorised
    mock_gemini.assert_called_once()
    
    assert processed[0]["category"] == "Food"
    assert processed[0]["llm_failed"] is False
    assert processed[1]["category"] == "Shopping" # Unchanged


@patch('app.services.llm_service.call_gemini_api')
def test_generate_narrative_summary(mock_gemini):
    mock_gemini.return_value = {
        "narrative": "Test narrative generated by LLM.",
        "risk_level": "medium"
    }
    
    settings.gemini_api_key = "test_key"
    
    records = [
        {"amount": 100, "currency": "INR", "merchant": "A", "category": "Food", "is_anomaly": False},
        {"amount": 50, "currency": "USD", "merchant": "A", "category": "Food", "is_anomaly": True},
        {"amount": 200, "currency": "INR", "merchant": "B", "category": "Travel", "is_anomaly": True},
    ]
    
    summary = generate_narrative_summary(records)
    
    assert summary["total_spend_inr"] == 300.0
    assert summary["total_spend_usd"] == 50.0
    assert summary["anomaly_count"] == 2
    assert summary["category_breakdown"] == {"Food": 150.0, "Travel": 200.0}
    assert summary["narrative"] == "Test narrative generated by LLM."
    assert summary["risk_level"] == "medium"
